### ISSUE TITLE
joint_state_publisher in metapackage robot depends on Qt

### ISSUE THREAD

**Issue by meyerj** [ros/metapackages#28]
Is it intentional that metapackage `robot` also depends on [joint_state_publisher](http://wiki.ros.org/joint_state_publisher)? Apparently it was like this for a long time.

It is the only GUI package that introduces a dependency on [python_qt_binding](http://wiki.ros.org/python_qt_binding) and hence Qt and X11. The [description of the metapackage](https://github.com/ros/metapackages/blob/20c6fe68aaca88813fa63821d3224865f28c9a10/robot/package.xml#L8) clearly states that "it may not contain any GUI dependencies".

Maybe a confusion with the `joint_state_listener` executable in package [robot_state_publisher](http://wiki.ros.org/robot_state_publisher)?

**Comment by meyerj** [comment]
Same for [actionlib](http://wiki.ros.org/actionlib), which is even listed in metapackage `ros_base`, but depends on [python-wxtools](https://github.com/ros/actionlib/blob/c89e440519eeb88a5005065a32330655c9450b8e/package.xml#L34) (https://github.com/ros/actionlib/issues/129).

**Comment by matthew-reynolds** [comment]
Looks like this is an artifact of the `robot_model` split-up. The old `robot_model` metapackage contained `joint_state_publisher`. 
 - Before melodic, the `robot` metapackage depended on `robot_model`, which pulled in `joint_state_publisher`.
 - Since melodic, with `robot_model` deprecated, the dependency is explicit.

Which means the issue has been present long before melodic as well. I didn't do a ton of digging, but it looks like `robot_model` has contained `joint_state_publisher` and therefore GUI dependencies [since 2013](https://github.com/ros/robot_model/commit/3ee9e5ab25db8b7c72c938262b254c89ca217e7d).

Also worth mentioning, the original discussion of REP 150 (ros-infrastructure/rep#144) doesn't mention the `joint_state_publisher` explicitly, it was just lumped in with the rest of the `robot_model` breakup. Looks like an oversight that's been carried forward for years and wasn't caught during the split-up.

---

@clalancette, since you seem to own REP 150:
 - Can `joint_state_publisher` be pulled out of `robot` and moved up to `desktop` in REP 150? If you okay this approach, I will open a PR.
 - I don't see an obvious easy solution for REP 142 unless we go the REP 150 route and replace `robot_model` with its constituent parts, not sure if that's a change we want to make as well.

---

Side note: Not sure it makes much of a difference, but should this discussion be moved to ros-infrastructure/rep? This repo is just the implementation of REP 142 & 150.

**Comment by clalancette** [comment]
I'm going to restrict this discussion to joint_state_publisher; we can discuss actionlib separately.

I'm reluctant to move things around in metapackages either for Melodic or earlier.  If we do that, we will almost certainly break someone who is depending on joint_state_publisher being in the robot metapackage.

Really, this all comes about because of the (mis-)design of joint_state_publisher.  Right now, when you launch joint_state_publisher, you can choose to show a GUI or not.  If you do choose to show a GUI, then it creates a PyQt window, etc.  But really, joint_state_publisher should be refactored to be 2 separate packages.  There would be a "base" package, where it does the basic joint_state_publisher things (no GUI), and a "GUI" package which depends on the "base" and adds a PyQt GUI to it.  We could then have the "base" one be a dependency of the robot metapackage, and the "GUI" one a dependency of the desktop metapackage.

@matthew-reynolds @meyerj , what do you think?

**Comment by matthew-reynolds** [comment]
Totally agree on the restricting to joint_state_publisher, actionlib discussion is already active elsewhere (ros/actionlib#133, in particular).

Understood with regards to pre-melodic changes. In that case should we remove the stipulation that `robot` "may not contain any GUI dependencies"? Both REP 142 and the metapackage description contain this statement.

I like the idea of separating the package, though I want to be careful about making breaking changes. Perhaps if the `use_gui` parameter is set true, we search for the new package (`joint_state_publisher_tools` or `[...]_gui` or something). If found, output a warning explaining the change and then launch the GUI node. If not found, output an error informing the user they must install the new package. Then, in Noetic, we can drop the `use_gui` parameter altogether.

As with [the discussion around splitting actionlib](https://github.com/ros/actionlib/pull/133#issuecomment-526306247), I suspect most people using the GUI of `joint_state_publisher` are doing so on a `desktop` or `desktop_full` install, so hopefully this shouldn't have too big of an impact.

**Comment by meyerj** [comment]
> @matthew-reynolds @meyerj , what do you think?

Splitting `joint_state_publisher` in two packages (or drop the GUI tool completely in favor of an equivalent rqt plugin package) sounds like the right path forward.

I found this issue while assembling a minimal ROS run-time build for our customers, but we use forks of all ROS repos anyway and it is easy to fix on our side.

**Comment by meyerj** [comment]
This issue was fixed in https://github.com/ros/joint_state_publisher/pull/31. Thanks!
